(declaim (optimize (debug 0) (safety 0) (speed 3)))
(ql:quickload "cl-mpm")
(ql:quickload "cl-mpm/setup")
(ql:quickload "vgplot")
(ql:quickload "swank.live")
(ql:quickload "cl-mpm/output")
(ql:quickload "magicl")

(defmacro time-form-noprint (form it)
  `(progn
    ;(declaim (optimize speed))
    (let* ((iterations ,it)
           (start (get-internal-real-time)))
      (dotimes (i iterations) ,form)
      (let* ((end (get-internal-real-time))
             (units internal-time-units-per-second)
             )
        (/ (- end start) (* iterations units))))))

(defun make-test-column (size)
  (let* ((sim (cl-mpm/setup::make-column 1 size)))
    (let* ((h (cl-mpm/mesh:mesh-resolution (cl-mpm:sim-mesh sim)))
           (e-scale 1)
           (h-x h)
           (h-y (/ h e-scale))
           (elements (* e-scale (- size 1)))
           )
      (setf (cl-mpm:sim-mps sim)
            (cl-mpm/setup::make-column-mps-elastic
              elements
              (list h-x h-y)
              1e4 0d0))) 
    (setf (cl-mpm:sim-damping-factor sim) 0)
    (setf (cl-mpm:sim-mass-filter sim) 0)
    sim
    ))


(defun test-throughput ()
  (progn
    (let* ((sizes (loop for i from 1 to 8 collect (expt 2 i)))
           (times (loop for size in sizes collect 
                        (let ((sim (make-test-column size)))
                          (progn
                            (format t "Testing size ~d ~%" size)
                            (time-form-noprint (cl-mpm::update-sim sim) 1000)))))
           (throughput (loop for dt in times collect (/ 1 dt)))
           )
      (values sizes times throughput)
      )))

(defun test-plot-throughput ()
  (multiple-value-bind (sizes times throughput) (test-throughput)
      (vgplot:close-all-plots)
      (vgplot:figure)
      (vgplot:xlabel "Size")
      (vgplot:ylabel "Throughput")
      (vgplot:plot sizes throughput)
      (vgplot:figure)
      (vgplot:loglog sizes times)
      (vgplot:xlabel "Size")
      (vgplot:ylabel "Time per step")))

(progn
  (defparameter *perf-sizes* '())
  (defparameter *perf-times* '())
  (defparameter *perf-throughput* '())
  (defparameter *test-corecount* '(1 2 4 8))
  (loop for cores in *test-corecount*
        do (progn
             (format t "Testing core count: ~d ~%" cores)
             (setf lparallel:*kernel* (lparallel:make-kernel cores :name "custom-kernel"))
             (multiple-value-bind (sizes times throughput) (test-throughput)
               (push sizes *perf-sizes*)
               (push times *perf-times*)
               (push throughput *perf-throughput*) 
               )))
  (vgplot:close-all-plots)
  (vgplot:figure)
  (vgplot:xlabel "Size")
  (vgplot:ylabel "Frame time")
  (apply #'vgplot:loglog (loop for i from 0 to (length *test-corecount*)
                           append (list (nth i *perf-sizes*) 
                                        (nth i *perf-times*)
                                        (format nil "~d" (nth i *test-corecount*)))))
  (vgplot:legend)
  (vgplot:figure)
  (vgplot:xlabel "Size")
  (vgplot:ylabel "Throughput")
  (apply #'vgplot:loglog (loop for i from 0 to (length *test-corecount*)
                           append (list (nth i *perf-sizes*) 
                                        (nth i *perf-throughput*)
                                        (format nil "~d" (nth i *test-corecount*)))))
  (vgplot:legend)
  )
;(setf lparallel:*kernel* (lparallel:make-kernel 1 :name "custom-kernel"))
;(test-throughput)
;(vgplot:figure)
