(in-package :cl-mpm/mpi)

(defmethod cl-mpm::update-sim ((sim mpm-sim-mpi-usf))
  (with-slots ((mesh cl-mpm::mesh)
               (mps  cl-mpm::mps)
               (bcs  cl-mpm::bcs)
               (bcs-force cl-mpm::bcs-force)
               (bcs-force-list cl-mpm::bcs-force-list)
               (dt cl-mpm::dt)
               (mass-filter cl-mpm::mass-filter)
               (split cl-mpm::allow-mp-split)
               (enable-damage cl-mpm::enable-damage)
               (nonlocal-damage cl-mpm::nonlocal-damage)
               (remove-damage cl-mpm::allow-mp-damage-removal)
               (fbar cl-mpm::enable-fbar)
               (vel-algo cl-mpm::velocity-algorithm)
               )
                sim
    (declare (type double-float mass-filter))
                (progn
                    ;; (exchange-mps sim)
                  (with-mpi-errors
                      (cl-mpm::reset-grid mesh)
                    (cl-mpm::p2g mesh mps vel-algo))
                  (mpi-sync-momentum sim)
                  (with-mpi-errors
                      (when (> mass-filter 0d0)
                        (cl-mpm::filter-grid mesh (cl-mpm::sim-mass-filter sim)))
                    (cl-mpm::apply-essential-bcs sim)
                    (cl-mpm::filter-cells sim)
                    (cl-mpm::update-node-kinematics sim)
                    (cl-mpm::apply-essential-bcs sim)
                    (cl-mpm::update-nodes sim)
                    (cl-mpm::update-filtered-cells sim))
                  (with-mpi-errors
                      (cl-mpm::update-stress mesh mps dt fbar)
                    (cl-mpm::update-stiffness-mps sim)
                    (cl-mpm::p2g-force sim)
                    (cl-mpm::apply-force-bcs sim dt))
                  (mpi-sync-force sim)
                  (with-mpi-errors
                      (cl-mpm::update-node-forces sim)
                    (cl-mpm::apply-essential-bcs sim)
                    (cl-mpm::reset-node-displacement sim)
                    (cl-mpm::update-nodes sim)
                    (cl-mpm::apply-essential-bcs sim)
                    (cl-mpm::g2p mesh mps dt vel-algo)
                    (cl-mpm::update-dynamic-stats sim)
                    (cl-mpm::new-loadstep sim))
                  (set-mp-mpi-index sim)
                  (exchange-mps sim 0d0)
                  (set-mp-mpi-index sim)
                  (clear-ghost-mps sim))))
(defmethod cl-mpm::update-sim ((sim mpm-sim-mpi-nodes-damage))
  (with-slots ((mesh cl-mpm::mesh)
               (mps  cl-mpm::mps)
               (bcs  cl-mpm::bcs)
               (bcs-force cl-mpm::bcs-force)
               (bcs-force-list cl-mpm::bcs-force-list)
               (dt cl-mpm::dt)
               (mass-filter cl-mpm::mass-filter)
               (split cl-mpm::allow-mp-split)
               (enable-damage cl-mpm::enable-damage)
               (nonlocal-damage cl-mpm::nonlocal-damage)
               (remove-damage cl-mpm::allow-mp-damage-removal)
               (fbar cl-mpm::enable-fbar)
               (vel-algo cl-mpm::velocity-algorithm)
               )
                sim
    (declare (type double-float mass-filter))
                (progn
                  (cl-mpm::reset-grid mesh)
                  (cl-mpm::p2g mesh mps vel-algo)
                  (mpi-sync-momentum sim)
                  (when (> mass-filter 0d0)
                    (cl-mpm::filter-grid mesh (cl-mpm::sim-mass-filter sim)))
                  (cl-mpm::update-node-kinematics sim)
                  (cl-mpm::apply-bcs mesh bcs dt)
                  (cl-mpm::update-stress mesh mps dt fbar)
                  (cl-mpm/damage::calculate-damage sim)
                  (cl-mpm::p2g-force sim)
                  (loop for bcs-f in bcs-force-list
                        do (cl-mpm::apply-bcs mesh bcs-f dt))
                  (mpi-sync-force sim)
                  (cl-mpm::update-node-forces sim)
                  (cl-mpm::apply-bcs mesh bcs dt)
                  (cl-mpm::update-dynamic-stats sim)
                  (cl-mpm::g2p mesh mps dt vel-algo)
                  (cl-mpm::update-particles sim)
                  (when remove-damage
                    (cl-mpm::remove-material-damaged sim))
                  (when split
                    (cl-mpm::split-mps sim))
                  (cl-mpm::check-mps sim)
                  ;; (cl-mpm::check-single-mps sim)
                  ;; (set-mp-mpi-index sim)
                  (exchange-mps sim 0d0)
                  (set-mp-mpi-index sim)
                  (clear-ghost-mps sim))))
